name: Better-BOT-Placeholders
version: 1.0
main: com.example.betterbotplaceholders.BetterBOTPlaceholders
api-version: 1.19
authors: [JustMentalMatt]
description: Provides PAPI placeholders for BungeeOnlineTime playtime tracking
depend: [PlaceholderAPI]